### ISSUE TITLE
Julia implementation error

### ISSUE THREAD

**Issue by lkno0705** [lkno0705/MatrixMultiplication#11]
After I ran the .bat file and started the .jl file I got some error printed to cmd. I attached a scrennshot of cmd. I also tried it after running the powershell script.
![Julia_Error](https://user-images.githubusercontent.com/43034754/76012131-0a015480-5f16-11ea-949b-8f4a267512c3.PNG)

**Comment by moorts** [comment]
Did you install Julia? It is interpreted so thats necessary. Also, if you did, you need to start the program with `julia matrix_mult.jl`

**Comment by lkno0705** [comment]
As you can see, I started the Julia script that way. I also installed Julia. I also got a julia interpreter in my windows apps. But I‘m not able to start it with julia .... I think the installer didn‘t added the bin dir to the PATH variable. Will check that later. Nevertheless I found a little workaround by assining the julia interpreter to the .jl file extension and the script did launch using the julia interpreter. But it did crashed with this error log. 
Another possible Problem I could think of is the Julia interpreter version, I installed the LTS version. Which one did you use?

**Comment by moorts** [comment]
I also used LTS (1.3.1). It seems like this workaround does not work properly (for whatever reason), since the program still executes correctly when I start it with the julia command line tool.

**Comment by lkno0705** [comment]
I'll take a look at my PATH Variable later today and try it again.

**Comment by lkno0705** [comment]
Fixed by installing current stable release (v1.31.0) instead of lts
