### ISSUE TITLE
PHP multithreading implementation

### ISSUE THREAD

**Issue by marcauberer** [lkno0705/MatrixMultiplication#14]
Threads in PHP are pretty messy: Threads are not officially supported by PHP. There is a [library](https://github.com/krakjoe/pthreads), which implements threads in C but this library is archived and gets no longer maintained. Since I'm testing on a Linux machine and I only found an executable version of the library for Windows, I was not able to test the script, but it should theoretically work. Maybe you can get the library work on your Windows system.

**Comment by lkno0705** [comment]
Could someone test the library on their windows machine over the weekend? @imkgerC  @moorts @nico1207 ? I won't be able to do it till monday.

Also what about the single core runtime on your machine (@marcauberer )? Do we still have the same problem with really long runtimes? If that's the case, we'll have to find a work around to benchmark the php implementation.

**Comment by marcauberer** [comment]
Actually yes. I've tested on a four-core server cpu with 2.8 GHz and got very bad results. Only for generating the random numbers on initialization, it needs about 20 seconds. For testing the program while implementing it, I used a smaller matrix size.
We should definitly find a solution for this problem.

**Comment by imkgerC** [comment]
By applying the optimizations found for MatrixMultiplcation_Python I was able to get the runtime of 240x240 multiplcation down from ~13s to 0.75s singlethreaded. I was not able to install the extension needed for multithreading (pthreads, I assume?). Could you provide guidance for that or put a README in the php folder with instructions?
btw: The optimizations are implemented in the php_optimization branch and are only implemented for singlethreading right now.

**Comment by marcauberer** [comment]
Great! I can't imagine where the huge time impact comes from?!
I will create a readme file and add a link to the gh repo of the pthreads library there.

**Comment by marcauberer** [comment]
Merged the branch to master. I would suggest to apply this optimization to all other languages to have a compareable result.

**Comment by imkgerC** [comment]
C, C++ and Rust should not experience benefits through this, as the compiler should already optimize that way. I don't have enough experience in the other languages to tell, if it is needed, but suspect that any decent optimizing compiler should handle this comparably well

**Comment by imkgerC** [comment]
BTW: A 540x540 Matrix now takes 11.5s on my machine, this should be fast enough to test on the full size, as python takes 14.7s under the same conditions. @lkno0705, testing on your machine is the last step missing, I suppose.

**Comment by lkno0705** [comment]
@imkgerC Did you manage to run a successful benchmark with multithreading?

**Comment by imkgerC** [comment]
No, but I didn't try that hard. php failed to load the extension library even though I was sure to have configured it correctly

**Comment by lkno0705** [comment]
So we‘ll stick with a singlecore benchmark then.

**Comment by marcauberer** [comment]
Yes. For now I would leave it like it is and benchmark only the single core performance.
