### ISSUE TITLE
Order languages in README by speed

### ISSUE THREAD

**Issue by marcauberer** [lkno0705/MatrixMultiplication#7]
I would suggest to reorder the programming languages in the readme file. I can imagine, that this would be more intuitive.
And btw: Please rerun the Kotlin benchmark. I just committed a bugfix.

**Comment by imkgerC** [comment]
Do you think it would be better to sort in ascending or descending order?

**Comment by marcauberer** [comment]
Would prefer an ascending order.

**Comment by lkno0705** [comment]
I would prefer alphabetical order.
